### ISSUE TITLE
JavaScript script for possible ball angle and trajectory

### ISSUE THREAD

**Issue by Ahmad-Bamba** [Team612/612-ProgrammingResources#2]
Talk to Mr. Gever.

**Comment by calvin-godfrey** [comment]
Ben sent me [this](https://www.desmos.com/calculator/uo20oacldq), I'm not sure if that's the same

**Comment by Ahmad-Bamba** [comment]
Other teams doing things before us, rip. I would say though, his script filtered out likely and possible combinations of angles and speeds, so you could filter based on realistic scenarios. If we wanted to, we could even combine it with Jishnu's ball scoring spreadsheet to differentiate it from other teams

**Comment by Ahmad-Bamba** [comment]
Completely up to you though, my goal isn't to just flood you all with busy work
