### ISSUE TITLE
Make the Favicon (the tiny logo in the tab) our logo

### ISSUE THREAD

**Issue by calvin-godfrey** [Team612/612-ProgrammingResources#6]
I'm not sure if it's possible, but Ben said it was. We probably have to do something with the host, not sure exactly what.

**Comment by Ahmad-Bamba** [comment]
The favicon is still the 000webhost one from when I tried to make that .xyz's host, so I think you're on the right track. Maybe @wardbenjamin can check on his side?

**Comment by calvin-godfrey** [comment]
Ben said he can do it, just hasn't had the time yet.
